name: 'thinkpaintfeel '
favicon: null
layout_spectrum: 0.014235606184229255
typography_spectrum: 0.4810392730869353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.034760849084705114
  lightness: 0.8465229871217161
  saturation: 0.6180467589292675
  rhythmicContrast: 0.530002988409251
purpose: []
